# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/meyo/Desktop/payroll_system/ui/admin_dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminDashboard(object):
    def setupUi(self, AdminDashboard):
        AdminDashboard.setObjectName("AdminDashboard")
        AdminDashboard.resize(1100, 680)
        self.centralwidget = QtWidgets.QWidget(AdminDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setProperty("contentsMargins", 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setObjectName("sidebar")
        self.sideLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.sideLayout.setProperty("contentsMargins", 0)
        self.sideLayout.setSpacing(2)
        self.sideLayout.setObjectName("sideLayout")
        self.appTitle = QtWidgets.QLabel(self.sidebar)
        self.appTitle.setObjectName("appTitle")
        self.sideLayout.addWidget(self.appTitle)
        self.appSub = QtWidgets.QLabel(self.sidebar)
        self.appSub.setObjectName("appSub")
        self.sideLayout.addWidget(self.appSub)
        self.btnNavDash = QtWidgets.QPushButton(self.sidebar)
        self.btnNavDash.setCheckable(True)
        self.btnNavDash.setChecked(True)
        self.btnNavDash.setObjectName("btnNavDash")
        self.sideLayout.addWidget(self.btnNavDash)
        self.btnNavEmp = QtWidgets.QPushButton(self.sidebar)
        self.btnNavEmp.setCheckable(True)
        self.btnNavEmp.setObjectName("btnNavEmp")
        self.sideLayout.addWidget(self.btnNavEmp)
        self.btnNavSalary = QtWidgets.QPushButton(self.sidebar)
        self.btnNavSalary.setCheckable(True)
        self.btnNavSalary.setObjectName("btnNavSalary")
        self.sideLayout.addWidget(self.btnNavSalary)
        self.btnNavLeave = QtWidgets.QPushButton(self.sidebar)
        self.btnNavLeave.setCheckable(True)
        self.btnNavLeave.setObjectName("btnNavLeave")
        self.sideLayout.addWidget(self.btnNavLeave)
        self.btnNavPayslip = QtWidgets.QPushButton(self.sidebar)
        self.btnNavPayslip.setCheckable(True)
        self.btnNavPayslip.setObjectName("btnNavPayslip")
        self.sideLayout.addWidget(self.btnNavPayslip)
        self.btnNavReport = QtWidgets.QPushButton(self.sidebar)
        self.btnNavReport.setCheckable(True)
        self.btnNavReport.setObjectName("btnNavReport")
        self.sideLayout.addWidget(self.btnNavReport)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sideLayout.addItem(spacerItem)
        self.lblUser = QtWidgets.QLabel(self.sidebar)
        self.lblUser.setObjectName("lblUser")
        self.sideLayout.addWidget(self.lblUser)
        self.btnLogout = QtWidgets.QPushButton(self.sidebar)
        self.btnLogout.setObjectName("btnLogout")
        self.sideLayout.addWidget(self.btnLogout)
        self.mainLayout.addWidget(self.sidebar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageDash = QtWidgets.QWidget()
        self.pageDash.setObjectName("pageDash")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.pageDash)
        self.vboxlayout.setProperty("contentsMargins", 24)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblDashTitle = QtWidgets.QLabel(self.pageDash)
        self.lblDashTitle.setObjectName("lblDashTitle")
        self.vboxlayout.addWidget(self.lblDashTitle)
        self.statsRow = QtWidgets.QHBoxLayout()
        self.statsRow.setObjectName("statsRow")
        self.cardEmp = QtWidgets.QFrame(self.pageDash)
        self.cardEmp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardEmp.setObjectName("cardEmp")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.cardEmp)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.valEmp = QtWidgets.QLabel(self.cardEmp)
        self.valEmp.setObjectName("valEmp")
        self.vboxlayout1.addWidget(self.valEmp)
        self.label = QtWidgets.QLabel(self.cardEmp)
        self.label.setObjectName("label")
        self.vboxlayout1.addWidget(self.label)
        self.statsRow.addWidget(self.cardEmp)
        self.cardAct = QtWidgets.QFrame(self.pageDash)
        self.cardAct.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardAct.setObjectName("cardAct")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.cardAct)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.valActive = QtWidgets.QLabel(self.cardAct)
        self.valActive.setObjectName("valActive")
        self.vboxlayout2.addWidget(self.valActive)
        self.label1 = QtWidgets.QLabel(self.cardAct)
        self.label1.setObjectName("label1")
        self.vboxlayout2.addWidget(self.label1)
        self.statsRow.addWidget(self.cardAct)
        self.cardLeave = QtWidgets.QFrame(self.pageDash)
        self.cardLeave.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardLeave.setObjectName("cardLeave")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.cardLeave)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.valLeave = QtWidgets.QLabel(self.cardLeave)
        self.valLeave.setObjectName("valLeave")
        self.vboxlayout3.addWidget(self.valLeave)
        self.label2 = QtWidgets.QLabel(self.cardLeave)
        self.label2.setObjectName("label2")
        self.vboxlayout3.addWidget(self.label2)
        self.statsRow.addWidget(self.cardLeave)
        self.cardPay = QtWidgets.QFrame(self.pageDash)
        self.cardPay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardPay.setObjectName("cardPay")
        self.vboxlayout4 = QtWidgets.QVBoxLayout(self.cardPay)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.valPayroll = QtWidgets.QLabel(self.cardPay)
        self.valPayroll.setObjectName("valPayroll")
        self.vboxlayout4.addWidget(self.valPayroll)
        self.label3 = QtWidgets.QLabel(self.cardPay)
        self.label3.setObjectName("label3")
        self.vboxlayout4.addWidget(self.label3)
        self.statsRow.addWidget(self.cardPay)
        self.vboxlayout.addLayout(self.statsRow)
        self.tblRecentPayslips = QtWidgets.QTableWidget(self.pageDash)
        self.tblRecentPayslips.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblRecentPayslips.setAlternatingRowColors(True)
        self.tblRecentPayslips.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblRecentPayslips.setColumnCount(5)
        self.tblRecentPayslips.setProperty("horizontalHeaderLabels", ['Employee ID', 'Name', 'Month/Year', 'Net Pay', 'Generated On'])
        self.tblRecentPayslips.setObjectName("tblRecentPayslips")
        self.tblRecentPayslips.setRowCount(0)
        self.vboxlayout.addWidget(self.tblRecentPayslips)
        self.stackedWidget.addWidget(self.pageDash)
        self.pageEmp = QtWidgets.QWidget()
        self.pageEmp.setObjectName("pageEmp")
        self.stackedWidget.addWidget(self.pageEmp)
        self.pageSalary = QtWidgets.QWidget()
        self.pageSalary.setObjectName("pageSalary")
        self.stackedWidget.addWidget(self.pageSalary)
        self.pageLeave = QtWidgets.QWidget()
        self.pageLeave.setObjectName("pageLeave")
        self.stackedWidget.addWidget(self.pageLeave)
        self.pagePayslip = QtWidgets.QWidget()
        self.pagePayslip.setObjectName("pagePayslip")
        self.stackedWidget.addWidget(self.pagePayslip)
        self.pageReport = QtWidgets.QWidget()
        self.pageReport.setObjectName("pageReport")
        self.stackedWidget.addWidget(self.pageReport)
        self.mainLayout.addWidget(self.stackedWidget)
        AdminDashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminDashboard)
        QtCore.QMetaObject.connectSlotsByName(AdminDashboard)

    def retranslateUi(self, AdminDashboard):
        _translate = QtCore.QCoreApplication.translate
        AdminDashboard.setWindowTitle(_translate("AdminDashboard", "Admin Dashboard – Payroll System"))
        AdminDashboard.setStyleSheet(_translate("AdminDashboard", "\n"
"    QMainWindow,QWidget { background-color: #1e2a3a; color: #c8d6e5; font-size: 13px; }\n"
"    QFrame#sidebar {\n"
"      background-color: #162031;\n"
"      border-right: 1px solid #2a3d55;\n"
"      min-width: 200px; max-width: 200px;\n"
"    }\n"
"    QLabel#appTitle { color:#ffffff; font-size:16px; font-weight:bold; padding:20px 16px 8px 16px; }\n"
"    QLabel#appSub   { color:#4a9eff; font-size:11px; padding:0 16px 20px 16px; }\n"
"    QPushButton.navBtn {\n"
"      background: transparent; color: #8a9bb0;\n"
"      border: none; border-radius: 6px;\n"
"      text-align: left; padding: 10px 16px;\n"
"      font-size: 13px;\n"
"    }\n"
"    QPushButton.navBtn:hover  { background:#1e2a3a; color:#ffffff; }\n"
"    QPushButton.navBtn:checked{ background:#4a9eff20; color:#4a9eff; border-left:3px solid #4a9eff; }\n"
"    QStackedWidget { background:#1e2a3a; }\n"
"    QFrame.card {\n"
"      background:#253447; border-radius:10px; padding:16px;\n"
"    }\n"
"    QLabel.cardValue { color:#ffffff; font-size:26px; font-weight:bold; }\n"
"    QLabel.cardTitle { color:#8a9bb0; font-size:12px; }\n"
"    QTableWidget {\n"
"      background:#253447; border:none; border-radius:8px;\n"
"      gridline-color:#2a3d55; color:#c8d6e5;\n"
"    }\n"
"    QTableWidget::item:selected { background:#4a9eff30; color:#ffffff; }\n"
"    QHeaderView::section { background:#1e2a3a; color:#8a9bb0; padding:8px; border:none; border-bottom:1px solid #2a3d55; }\n"
"    QPushButton#btnLogout {\n"
"      background:#e74c3c; color:#ffffff; border:none;\n"
"      border-radius:6px; padding:8px 16px; font-weight:bold;\n"
"    }\n"
"    QPushButton#btnLogout:hover { background:#c0392b; color:#ffffff; }\n"
"   "))
        self.appTitle.setText(_translate("AdminDashboard", "💼 PayrollPro"))
        self.appSub.setText(_translate("AdminDashboard", "Admin Panel"))
        self.btnNavDash.setText(_translate("AdminDashboard", "🏠  Dashboard"))
        self.btnNavEmp.setText(_translate("AdminDashboard", "👥  Employees"))
        self.btnNavSalary.setText(_translate("AdminDashboard", "💰  Salary"))
        self.btnNavLeave.setText(_translate("AdminDashboard", "🗓  Leave"))
        self.btnNavPayslip.setText(_translate("AdminDashboard", "🧾  Payslips"))
        self.btnNavReport.setText(_translate("AdminDashboard", "📊  Reports"))
        self.lblUser.setStyleSheet(_translate("AdminDashboard", "color:#8a9bb0; padding:8px 16px;"))
        self.lblUser.setText(_translate("AdminDashboard", "               👤 Admin"))
        self.btnLogout.setStyleSheet(_translate("AdminDashboard", "margin:8px 16px 16px 16px; background-color:#e74c3c; color:#ffffff; border:none; border-radius:6px; font-weight:bold; font-size:13px;"))
        self.btnLogout.setText(_translate("AdminDashboard", "Logout"))
        self.lblDashTitle.setStyleSheet(_translate("AdminDashboard", "font-size:20px;font-weight:bold;color:#fff;"))
        self.lblDashTitle.setText(_translate("AdminDashboard", "Dashboard Overview"))
        self.valEmp.setStyleSheet(_translate("AdminDashboard", "color:#4a9eff;font-size:28px;font-weight:bold;"))
        self.valEmp.setText(_translate("AdminDashboard", "0"))
        self.label.setStyleSheet(_translate("AdminDashboard", "color:#8a9bb0;"))
        self.label.setText(_translate("AdminDashboard", "Total Employees"))
        self.valActive.setStyleSheet(_translate("AdminDashboard", "color:#2ecc71;font-size:28px;font-weight:bold;"))
        self.valActive.setText(_translate("AdminDashboard", "0"))
        self.label1.setStyleSheet(_translate("AdminDashboard", "color:#8a9bb0;"))
        self.label1.setText(_translate("AdminDashboard", "Active Employees"))
        self.valLeave.setStyleSheet(_translate("AdminDashboard", "color:#f39c12;font-size:28px;font-weight:bold;"))
        self.valLeave.setText(_translate("AdminDashboard", "0"))
        self.label2.setStyleSheet(_translate("AdminDashboard", "color:#8a9bb0;"))
        self.label2.setText(_translate("AdminDashboard", "Pending Leaves"))
        self.valPayroll.setStyleSheet(_translate("AdminDashboard", "color:#9b59b6;font-size:28px;font-weight:bold;"))
        self.valPayroll.setText(_translate("AdminDashboard", "₱0"))
        self.label3.setStyleSheet(_translate("AdminDashboard", "color:#8a9bb0;"))
        self.label3.setText(_translate("AdminDashboard", "Monthly Payroll"))
